### ISSUE TITLE
API: Metrics(), Transactions(), SpammingErrors() for getting the current spammer state

### ISSUE THREAD

**Issue by luca-moser** [iota-tangle-io/iota-spamalot.go#5]
In order to let the coordinator know the state of the spammer, we need some data from it.

`Metrics()` which returns following things:
* current transaction per second
* failure rate over one minute
* load of the system (where as this can be left out for now)
* ...?

`Transactions()`:
* all created transactions with time stamp and hash

`SpammingErrors()`:
* returns error messages being "thrown" while spamming (with time stamps)

The idea is that the coordinator has enough data to conclude a health property of a slave.

**Comment by cwarner818** [comment]
I think storing these things in memory could be a bad idea. In the case of 1 transaction per second, thats a decent amount of data generated. It might be better to stream these back to the coordinator in real time over the websocket. 

Aside from that I think these are great metrics to track and will work towards collecting them in the spamalot package.

**Comment by luca-moser** [comment]
Yeah, it would be better then if the functions would return a channel from which all that data can be read. I agree that all those values shouldn't be hold in memory by the spammer.

Obviously the spammer would only send data on the channels if requested by the instantiator of the spammer.

The data stream would then be sent to the coordinator from the slave via WebSocket, which in turn saves it to the database.
